name: Portainer CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[portainer]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_vars
          token: ${{secrets.PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: Logotipiwe/dc_infrastructure
          token: ${{secrets.PAT}}
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: infra
          remote: /kuber/infra
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.DC_HOST}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            cd /kuber/infra/
            docker-compose -f portainer.yml pull
            docker-compose -f portainer.yml up -d --no-deps --force-recreate